# This workflow will run the backtesting of QDII premium arbitrary strategy, save the result to release
name: backtesting-qdii-premium-nasdaq100

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00. (midnight)


jobs:

  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: my-backtesting

    steps:
    - uses: actions/checkout@v2
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Python script
      run: |
        python nasdaq_analysis.py
        
    - name: List everything
      run: |
        ls -al

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output-files
        path: |
          my-backtesting/myorders.csv
          my-backtesting/mystats.csv
          my-backtesting/other_stats.csv
          my-backtesting/result.png
    
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"


    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: qdii-premium-nasdaq100 ${{ steps.date.outputs.date }}
        release_name: qdii-premium-nasdaq100 ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
        
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: output-files

    - name: Upload myorders
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: myorders.csv
        asset_name: nasdaq100-myorders.csv
        asset_content_type: text/plain
        
    - name: Upload mystats
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: mystats.csv
        asset_name: nasdaq100-mystats.csv
        asset_content_type: text/plain
        
    - name: Upload other_stats
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: other_stats.csv
        asset_name: nasdaq100-other_stats.csv
        asset_content_type: text/plain

    - name: Upload result.png
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: result.png
        asset_name: nasdaq100-result.png
        asset_content_type: image/png

